export const quizQuestions = [
  { id: "1", question: "Which domain of cyber security focuses on protecting devices that connect to the network, such as laptops and phones?", options: ["Network security", "Application security", "Endpoint security", "Cloud security"], correctIndex: 2, explanation: "Endpoint security covers laptops, phones, and other devices that connect to the network. Network security focuses on the network itself; application and cloud security target apps and cloud infrastructure." },
  { id: "2", question: "What is phishing?", options: ["A type of hardware failure", "Attempts to trick you into revealing credentials or data via fake emails or sites", "A form of encryption", "A backup strategy"], correctIndex: 1, explanation: "Phishing uses fake emails or websites to trick people into giving up passwords, payment details, or other sensitive data. Always verify links and senders before clicking or replying." },
  { id: "3", question: "Why is two-factor authentication (2FA) recommended?", options: ["It makes passwords longer", "It adds a second check so stolen passwords alone are not enough", "It replaces the need for passwords", "It is required by law"], correctIndex: 1, explanation: "2FA requires a second factor (e.g. a code on your phone) in addition to your password. Even if someone steals your password, they usually cannot complete the second step." },
  { id: "4", question: "What does 'least privilege' mean in security?", options: ["Users should have as few permissions as possible", "Everyone gets admin access", "Passwords should be short", "Only one person can log in at a time"], correctIndex: 0, explanation: "Least privilege means giving each user or process only the minimum access needed to do their job. This limits the damage if an account is compromised." },
  { id: "5", question: "Which threat encrypts your data and demands payment to restore it?", options: ["Phishing", "DDoS", "Ransomware", "Social engineering"], correctIndex: 2, explanation: "Ransomware encrypts files and demands a ransom (often in cryptocurrency) to provide the decryption key. Backups and good hygiene reduce the impact." },
  { id: "6", question: "What is a key practice to reduce the impact of ransomware?", options: ["Pay the ransom quickly", "Keep regular backups, including offline or immutable copies", "Disable antivirus", "Share passwords with IT"], correctIndex: 1, explanation: "Regular backups that are offline or immutable can let you restore data without paying. Paying the ransom funds criminals and does not guarantee recovery." },
  { id: "7", question: "What does IAM stand for in cyber security?", options: ["Internal Audit Method", "Identity and Access Management", "Intrusion Alert Module", "Internet Access Monitor"], correctIndex: 1, explanation: "Identity and Access Management (IAM) covers how identities are created, stored, and used to control who can access which systems and data." },
  { id: "8", question: "What is zero trust?", options: ["A model that assumes no user or device is trusted by default", "A type of antivirus", "A backup technology", "A single sign-on product"], correctIndex: 0, explanation: "Zero trust assumes the network is already hostile. Access is verified continuously and granted only to what is needed, regardless of where the user or device is." },
  { id: "9", question: "What does DDoS stand for?", options: ["Data Deletion on System", "Distributed Denial-of-Service", "Direct Download of Software", "Default Domain of Security"], correctIndex: 1, explanation: "A Distributed Denial-of-Service attack floods a service with traffic from many sources so that legitimate users cannot access it." },
  { id: "10", question: "Why is supply chain security important?", options: ["It only affects large companies", "Attackers can target suppliers to reach many victims", "It replaces the need for firewalls", "It is only relevant to physical goods"], correctIndex: 1, explanation: "Attackers can compromise a single supplier (e.g. software vendor) and then affect all of that supplier’s customers. Securing the supply chain reduces this risk." },
  { id: "11", question: "What is social engineering?", options: ["A type of software patch", "Manipulating people into giving up information or access", "A form of encryption", "A network topology"], correctIndex: 1, explanation: "Social engineering targets people rather than systems—e.g. pretexting, phishing, or impersonation—to obtain information or access. Awareness and verification help defend against it." },
  { id: "12", question: "Which practice helps ensure data can be recovered after a ransomware attack?", options: ["Using a long password", "Regular tested backups", "Disabling updates", "Sharing accounts"], correctIndex: 1, explanation: "Regular backups that are tested (so you know they work) allow you to restore data without paying the ransom. Backups should be kept offline or otherwise protected from encryption by the same attack." },
];
